# Generated by Django 3.0.8 on 2020-07-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200720_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='documents1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='documents2',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents1', models.CharField(max_length=60, null=True)),
                ('documents2', models.CharField(max_length=60, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
