# Generated by Django 3.0.8 on 2020-07-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200720_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='wilay',
            new_name='wilaya',
        ),
    ]
